### ISSUE TITLE
Can this bump micromatch in a minor or patch?

### ISSUE THREAD

**Issue by phated** [micromatch/anymatch#22]
@jonschlinkert @doowb Can this module bump to micromatch 3.x as a minor or patch bump?  I believe it's stated that micromatch shouldn't have had any breaking changes.

I bring this up because I'm noticing a ton of duplication in my dependency graph due to this outdated version of micromatch.

**Comment by jonschlinkert** [comment]
micromatch 3.0 might be stricter with escaping, but no new rules were introduced intentionally. If @es128 is okay with it, I think a patch would be okay. If any tests break, or any issues occur, please forward them over to micromatch and I'll get it fixed.

**Comment by realityking** [comment]
I just noticed the same thing as @phated. Any update @es128 or @jonschlinkert?

**Comment by jonschlinkert** [comment]
After re-reading my previous comment, I don't think we should patch, I think it should be a major bump. These globbing libs are more prone to edge cases than the average lib so I'd play it safe. Just my 2c.

@es128 if someone submits a pr with all tests passing would you be open to it? @phated have you tried upgrading micromatch to 3.0? Notice any issues? 

(also, fwiw I finally got a windows box that I can use for debugging and tests if we run into windows path issues)

**Comment by es128** [comment]
I'm fine with upgrading in a major bump.

The intersection of prior support for backslash separators on windows and new support for proper escaping probably makes anything less than major inappropriate, but if someone wants to do some legwork to evaluate the impacts and make a case I'm open to listening.

**Comment by phated** [comment]
Based on the issues I see pop up on the glob libraries, I think it's best to major bump.

**Comment by phated** [comment]
@es128 can we bump this major?

**Comment by phated** [comment]
Closed by #23
