### ISSUE TITLE
Updating micromatch to 3.1.10 to prevent vulnerability

### ISSUE THREAD

**Issue by amiral84** [micromatch/anymatch#26]
Hi,

There is vulneralibity issue with braces 2.3.0. The fix comes with braces version 2.3.1 or later. Micromatch is using braces and they have already updated their version of braces. Micromatch current version when I'm writing this issue is 3.1.10. This contains the updated version of braces. I noticed that you are currently using 3.1.4 of micromatch. Could you update Anymatch's micromatch version to 3.1.10?

More info about braces vulnerability at https://nodesecurity.io/advisories/786

**Comment by Adam-Kernig** [comment]
+ 1 this

**Comment by doowb** [comment]
The way semver works is that you'll get version `3.1.10` if the package.json specifies `3.1.4`. If you're not, then you need to upgrade or remove and recreate or you lock files.

**Comment by jonschlinkert** [comment]
@Adam-Kernig you should probably close the related spam issues you created as well.
